apple:
  client-id: ${APPLE_CLIENT_ID:your.app.bundle.id}
  redirect-uri: ${APPLE_REDIRECT_URI:https://your-app.com/auth/apple/callback}
  aud: ${APPLE_AUD:https://appleid.apple.com}
  team-id: ${APPLE_TEAM_ID:YOUR_TEAM_ID}
  key-id: ${APPLE_KEY_ID:YOUR_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY:BASE64_ENCODED_PRIVATE_KEY}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  url: ${SERVER_URL:http://localhost:8080}

logging:
  level:
    com.dpm05.user: DEBUG
    org.springframework.security: DEBUG