name: 통합 CI/CD [Stock Diary] Container Build, Push & Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Server Environment'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit