name: PR Code Style Check

on:
  pull_request:
    branches: [ develop, main ]
    paths:
      - '**/*.java'
      - '**/build.gradle*'
      - '.github/workflows/**'

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Grant execute permission for Gradle
        run: chmod +x ./stock-diary/gradlew
        
      - name: Code Style Check
        working-directory: ./stock-diary
        run: ./gradlew spotlessCheck --no-daemon