name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --no-daemon


      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - uses: dkershner6/aws-ssm-getparameters-action@v2
        id: ssm
        with:
          parameterPairs: |
            /ci/ec2/host = EC2_HOST
            /ci/ec2/user = EC2_USER
            /ci/ec2/private_key = EC2_PRIVATE_KEY
            /ci/ec2/ssh_port = EC2_SSH_PORT

          # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
          # No limit on number of parameters. You can put new lines and spaces in as desired, they get trimmed out.
          withDecryption: "true" # defaults to true

      - name: Export EC2_PRIVATE_KEY safely
        run: |
          echo "EC2_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          echo "${{ env.EC2_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: ssh to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: ${{ env.EC2_SSH_PORT }}

          script: |
            cd /home/ubuntu/depromeet &&
            git checkout develop &&
            git fetch --all &&
            git reset --hard origin/develop &&
            ./gradlew build
            
            
          
      
            
            
            
            
        
