name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build stock-diary module
        run: ./gradlew :stock-diary:build --no-daemon

      - name: Verify stock-diary JAR creation
        run: |
          if [ -f "stock-diary/build/libs/stock-diary-0.0.1-SNAPSHOT.jar" ]; then
            echo "✅ Stock-diary JAR successfully built"
            ls -la stock-diary/build/libs/
          else
            echo "❌ Stock-diary JAR not found"
            exit 1
          fi

      - name: Upload stock-diary artifact
        uses: actions/upload-artifact@v3
        with:
          name: stock-diary-jar
          path: stock-diary/build/libs/stock-diary-0.0.1-SNAPSHOT.jar
          retention-days: 30
